(env
 (dev
  (ocamlopt_flags (:standard -g -ccopt -fopenmp)))
 (dev-static
  (ocamlopt_flags (:standard -g -ccopt -fopenmp -ccopt -static)))
 (release
  (ocamlopt_flags (:standard -O3 -ccopt -O3 -ccopt -fopenmp)))
 (release-static
  (ocamlopt_flags (:standard -O3 -ccopt -O3 -ccopt -fopenmp -ccopt -static))))

(executable
 (public_name DistanceIterator)
 (name DistanceIterator)
 (libraries str unix BiOCamLib KPop))

(executables
 (public_names CA RSVD Epsilon Cluster Splits)
 (names CA RSVD Epsilon Cluster Splits)
 (libraries str unix BiOCamLib KPop)
 (link_flags (-cclib -lgfortran -cclib -lquadmath -cclib -lstdc++)))

